### ISSUE TITLE
ScummVM doesn't backed up

### ISSUE THREAD

**Issue by gloony** [ridgekuhn/arklone-retropie#2]
I have some file with extension "sg0", "sg1", "sg2", ... and file "timestamps" for saved file of scummvm but they doesn't backed up by our script.
I have already manually set the folder for save to "configs\all\retroarch\saves\scummvm".

**Comment by ridgekuhn** [comment]
@gloony Hello, thx for trying it out! It sounds like you're using the ScummVM RetroArch core, not the standalone ScummVM? If it's the RetroArch core, all u need to do is edit a couple files. I apologize, it's been several years since I wrote this plugin so I forget where RetroPie stores it, but if u navigate to that directory, then src/rclone/filters/, you can add filters for each of the sync modules. Edit both retroarch.filter and retroarch-savefiles.filter and add a line like below to the top of each file. See [Rclone Filtering](https://rclone.org/filtering/) for the full syntax you can use inside this file. 

```
+ *.sg*
```

**Comment by ridgekuhn** [comment]
@gloony I'm not sure if this works, but it would be more appropriate:

```
+ {{ .*\.sg\d* }}
```

ps, it sounds like u modified the save path in your main retroarch.cfg, so in case u haven't done it yet, be sure to run the "regenerate path units" option in the arklone dialog so it can know about the new path

**Comment by gloony** [comment]
Thank you for your quick response on your old project :)
I would give you a positive feedback because it work well !

I use the main ScummVM emulator from Retropie.

I tried yesterday to modify already the retroarch.filter and retroarch-savefiles.filter but I have trouble to build it from retropie.
I even made a fork trying to add it from a source but I lack training to do it quickly and all my test build it from your source.

When I make it work, I will make a PR in probably a couple of day.

**Comment by ridgekuhn** [comment]
@gloony I see, if you're using the standalone version of ScummVM, you'll have to extend arklone. You really only have to make a couple files, but the whole thing is kind of a mess bc I didn't realize until after I had written the whole thing that systemd path units aren't capable of recursively watching a directory. It's one of the reasons I haven't updated the project, because I feel like it just needs to be rewritten from the ground up. Anyway, if u want to try your hand at it, u can see the [dev docs](https://github.com/ridgekuhn/arklone-retropie/blob/master/DEVELOPERS.md). I think the oga_controls section can be safely ignored as that was for the ArkOS version of arklone and RetroPie has its own method of handling inputs for shell scripts launched from Emulationstation.

**Comment by gloony** [comment]
I don't thing it is a big issue because you can edit save path of ScummVM on the main interface.
So my save file is already on config folders of retroarch.

I want to believe that Filter would do the job.

I will keep you in touch.

**Comment by ridgekuhn** [comment]
@gloony Oh, that’s a smart idea, u could use either RetroArch or standalone! Hope it works out!

**Comment by gloony** [comment]
I am able to save my "timestamps", "sg*", "s*" file but it appear that every file is named differently by game in scummvm 😭 

![image](https://github.com/ridgekuhn/arklone-retropie/assets/32897194/734b99cf-3313-4608-9e7a-28cc2e42b76d)

**Comment by gloony** [comment]
I ended by modify retroarch.filter and retroarch-savefile.filter by only "+ *".
It work fine like that but I don't understand what I risk with this configuration since it observe only the folder of save file.

**Comment by ridgekuhn** [comment]
@gloony Hmm, it depends on your config, but in your case, I'd say you risk nothing. The reason they're separated out into those 3 files was to support all possible retroarch.cfg scenarios, where savefiles/savestates might be in the same dir as files you might not want to sync

**Comment by gloony** [comment]
After setting up my PiBoy and GPICase, and trying to sync the saves, I can tell that it solved all of my problems.
I'm closing the case :). Thank you for your availability.

**Comment by ridgekuhn** [comment]
@gloony Glad it worked out for you!
